// Code generated by protoc-gen-connect-csharp. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using ConnectNet;
using ConnectNet.Client;
using ConnectNet.Server;
using Google.Protobuf;

namespace Connectrpc.Conformance.V1;

public static class ConformanceServiceMethods
{
    public const string ServiceName = "connectrpc.conformance.v1.ConformanceService";
    public const string Unary = "/connectrpc.conformance.v1.ConformanceService/Unary";
    public const string ServerStream = "/connectrpc.conformance.v1.ConformanceService/ServerStream";
    public const string ClientStream = "/connectrpc.conformance.v1.ConformanceService/ClientStream";
    public const string BidiStream = "/connectrpc.conformance.v1.ConformanceService/BidiStream";
    public const string Unimplemented = "/connectrpc.conformance.v1.ConformanceService/Unimplemented";
    public const string IdempotentUnary = "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary";
}

// --- Client ---

public interface IConformanceServiceClient
{
    Task<UnaryResponse> UnaryAsync(UnaryRequest request, CallOptions? options = null, CancellationToken ct = default);
    IAsyncEnumerable<ServerStreamResponse> ServerStreamAsync(ServerStreamRequest request, CallOptions? options = null, CancellationToken ct = default);
    ClientStreamCall<ClientStreamRequest, ClientStreamResponse> ClientStreamAsync(CallOptions? options = null, CancellationToken ct = default);
    BidiStreamCall<BidiStreamRequest, BidiStreamResponse> BidiStreamAsync(CallOptions? options = null, CancellationToken ct = default);
    Task<UnimplementedResponse> UnimplementedAsync(UnimplementedRequest request, CallOptions? options = null, CancellationToken ct = default);
    Task<IdempotentUnaryResponse> IdempotentUnaryAsync(IdempotentUnaryRequest request, CallOptions? options = null, CancellationToken ct = default);
}

public class ConformanceServiceClient : IConformanceServiceClient
{
    private readonly ConnectChannel _channel;
    public ConformanceServiceClient(ConnectChannel channel) => _channel = channel;

    public Task<UnaryResponse> UnaryAsync(UnaryRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.UnaryAsync<UnaryRequest, UnaryResponse>(ConformanceServiceMethods.Unary, request, options, ct);

    public IAsyncEnumerable<ServerStreamResponse> ServerStreamAsync(ServerStreamRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.ServerStreamAsync<ServerStreamRequest, ServerStreamResponse>(ConformanceServiceMethods.ServerStream, request, options, ct);

    public ClientStreamCall<ClientStreamRequest, ClientStreamResponse> ClientStreamAsync(CallOptions? options = null, CancellationToken ct = default)
        => _channel.ClientStreamAsync<ClientStreamRequest, ClientStreamResponse>(ConformanceServiceMethods.ClientStream, options, ct);

    public BidiStreamCall<BidiStreamRequest, BidiStreamResponse> BidiStreamAsync(CallOptions? options = null, CancellationToken ct = default)
        => _channel.BidiStreamAsync<BidiStreamRequest, BidiStreamResponse>(ConformanceServiceMethods.BidiStream, options, ct);

    public Task<UnimplementedResponse> UnimplementedAsync(UnimplementedRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.UnaryAsync<UnimplementedRequest, UnimplementedResponse>(ConformanceServiceMethods.Unimplemented, request, options, ct);

    public Task<IdempotentUnaryResponse> IdempotentUnaryAsync(IdempotentUnaryRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.UnaryAsync<IdempotentUnaryRequest, IdempotentUnaryResponse>(ConformanceServiceMethods.IdempotentUnary, request, options, ct);

}

// --- Server ---

public abstract class ConformanceServiceBase
{
    public virtual Task<UnaryResponse> Unary(UnaryRequest request, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "Unary is not implemented");

    public virtual IAsyncEnumerable<ServerStreamResponse> ServerStream(ServerStreamRequest request, ConnectContext context, CancellationToken ct = default)
        => throw new ConnectException(ConnectCode.Unimplemented, "ServerStream is not implemented");

    public virtual Task<ClientStreamResponse> ClientStream(IAsyncEnumerable<ClientStreamRequest> requests, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "ClientStream is not implemented");

    public virtual IAsyncEnumerable<BidiStreamResponse> BidiStream(IAsyncEnumerable<BidiStreamRequest> requests, ConnectContext context, CancellationToken ct = default)
        => throw new ConnectException(ConnectCode.Unimplemented, "BidiStream is not implemented");

    public virtual Task<UnimplementedResponse> Unimplemented(UnimplementedRequest request, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "Unimplemented is not implemented");

    public virtual Task<IdempotentUnaryResponse> IdempotentUnary(IdempotentUnaryRequest request, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "IdempotentUnary is not implemented");

}

public class ConformanceServiceDefinition : IConnectServiceDefinition
{
    public static ConformanceServiceDefinition Instance { get; } = new();
    public string ServiceName => ConformanceServiceMethods.ServiceName;
    public IReadOnlyList<ConnectMethodDescriptor> Methods { get; } = new ConnectMethodDescriptor[]
    {
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.Unary,
            UnaryRequest.Parser,
            handler: async (svc, req, ctx) => (IMessage)await ((ConformanceServiceBase)svc).Unary((UnaryRequest)req, ctx)),
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.ServerStream,
            ServerStreamRequest.Parser,
            methodType: ConnectMethodType.ServerStreaming,
            serverStreamHandler: (svc, req, ctx) => ConvertStream(((ConformanceServiceBase)svc).ServerStream((ServerStreamRequest)req, ctx))),
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.ClientStream,
            ClientStreamRequest.Parser,
            methodType: ConnectMethodType.ClientStreaming,
            clientStreamHandler: async (svc, reqs, ctx) => (IMessage)await ((ConformanceServiceBase)svc).ClientStream(ConvertStream<ClientStreamRequest>(reqs), ctx)),
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.BidiStream,
            BidiStreamRequest.Parser,
            methodType: ConnectMethodType.BidiStreaming,
            bidiStreamHandler: (svc, reqs, ctx) => ConvertStream(((ConformanceServiceBase)svc).BidiStream(ConvertStream<BidiStreamRequest>(reqs), ctx))),
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.Unimplemented,
            UnimplementedRequest.Parser,
            handler: async (svc, req, ctx) => (IMessage)await ((ConformanceServiceBase)svc).Unimplemented((UnimplementedRequest)req, ctx)),
        new ConnectMethodDescriptor(
            ConformanceServiceMethods.IdempotentUnary,
            IdempotentUnaryRequest.Parser,
            handler: async (svc, req, ctx) => (IMessage)await ((ConformanceServiceBase)svc).IdempotentUnary((IdempotentUnaryRequest)req, ctx),
            isNoSideEffects: true)
    };

    private static async IAsyncEnumerable<IMessage> ConvertStream<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage
    {
        await foreach (var item in source.WithCancellation(ct))
            yield return item;
    }

    private static async IAsyncEnumerable<T> ConvertStream<T>(IAsyncEnumerable<IMessage> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage
    {
        await foreach (var item in source.WithCancellation(ct))
            yield return (T)item;
    }

}
