<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ConnectNet/ConnectNet.csproj" />
    <ProjectReference Include="../../src/ConnectNet.Client/ConnectNet.Client.csproj" />
    <ProjectReference Include="../../src/ConnectNet.Server/ConnectNet.Server.csproj" />
    <ProjectReference Include="../ConnectNet.Tests.Proto/ConnectNet.Tests.Proto.csproj" />
    <ProjectReference Include="../../src/ConnectNet.Validation/ConnectNet.Validation.csproj" />
  </ItemGroup>
</Project>
