package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if file.Generate {
				if err := generateFile(plugin, file); err != nil {
					return err
				}
			}
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	if len(file.Services) == 0 {
		return nil
	}

	csNamespace := getCSharpNamespace(file)

	for _, service := range file.Services {
		// Use the proto file's directory for the output path, not Go import paths
		protoPath := file.Desc.Path()
		dir := filepath.Dir(protoPath)
		filename := string(service.GoName) + ".connect.cs"
		if dir != "." && dir != "" {
			filename = dir + "/" + filename
		}
		g := plugin.NewGeneratedFile(filename, "")
		generateService(g, file, service, csNamespace)
	}

	return nil
}

func getCSharpNamespace(file *protogen.File) string {
	if opts := file.Desc.Options(); opts != nil {
		fdp, ok := opts.(*descriptorpb.FileOptions)
		if ok && fdp.CsharpNamespace != nil {
			return *fdp.CsharpNamespace
		}
	}
	// Derive from package name: capitalize each segment
	pkg := string(file.Desc.Package())
	if pkg == "" {
		return ""
	}
	parts := strings.Split(pkg, ".")
	for i, p := range parts {
		parts[i] = pascalCase(p)
	}
	return strings.Join(parts, ".")
}

func pascalCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	// Convert snake_case to PascalCase
	result := make([]rune, 0, len(runes))
	capitalizeNext := true
	for _, r := range runes {
		if r == '_' {
			capitalizeNext = true
			continue
		}
		if capitalizeNext {
			result = append(result, unicode.ToUpper(r))
			capitalizeNext = false
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}

func generateService(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service, csNamespace string) {
	serviceName := string(service.GoName)
	protoServiceName := fmt.Sprintf("%s.%s", file.Desc.Package(), service.Desc.Name())

	p := func(format string, args ...interface{}) {
		fmt.Fprintf(g, format+"\n", args...)
	}

	// Preamble
	p("// Code generated by protoc-gen-connect-csharp. DO NOT EDIT.")
	p("")
	p("using System;")
	p("using System.Collections.Generic;")
	p("using System.Runtime.CompilerServices;")
	p("using System.Threading;")
	p("using System.Threading.Tasks;")
	p("using ConnectNet;")
	p("using ConnectNet.Client;")
	p("using ConnectNet.Server;")
	p("using Google.Protobuf;")
	p("")

	if csNamespace != "" {
		p("namespace %s;", csNamespace)
	}
	p("")

	// --- Methods static class ---
	p("public static class %sMethods", serviceName)
	p("{")
	p("    public const string ServiceName = \"%s\";", protoServiceName)
	for _, method := range service.Methods {
		methodName := string(method.GoName)
		p("    public const string %s = \"/%s/%s\";", methodName, protoServiceName, method.Desc.Name())
	}
	p("}")
	p("")

	// --- Client Interface ---
	p("// --- Client ---")
	p("")
	p("public interface I%sClient", serviceName)
	p("{")
	for _, method := range service.Methods {
		methodName := string(method.GoName)
		inputType := csharpMessageType(method.Input)
		outputType := csharpMessageType(method.Output)

		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			// Unary
			p("    Task<%s> %sAsync(%s request, CallOptions? options = null, CancellationToken ct = default);",
				outputType, methodName, inputType)
		case !method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			// Server streaming
			p("    IAsyncEnumerable<%s> %sAsync(%s request, CallOptions? options = null, CancellationToken ct = default);",
				outputType, methodName, inputType)
		case method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			// Client streaming
			p("    ClientStreamCall<%s, %s> %sAsync(CallOptions? options = null, CancellationToken ct = default);",
				inputType, outputType, methodName)
		case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			// Bidi streaming
			p("    BidiStreamCall<%s, %s> %sAsync(CallOptions? options = null, CancellationToken ct = default);",
				inputType, outputType, methodName)
		}
	}
	p("}")
	p("")

	// --- Client Implementation ---
	p("public class %sClient : I%sClient", serviceName, serviceName)
	p("{")
	p("    private readonly ConnectChannel _channel;")
	p("    public %sClient(ConnectChannel channel) => _channel = channel;", serviceName)
	p("")

	for _, method := range service.Methods {
		methodName := string(method.GoName)
		inputType := csharpMessageType(method.Input)
		outputType := csharpMessageType(method.Output)

		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			p("    public Task<%s> %sAsync(%s request, CallOptions? options = null, CancellationToken ct = default)",
				outputType, methodName, inputType)
			p("        => _channel.UnaryAsync<%s, %s>(%sMethods.%s, request, options, ct);",
				inputType, outputType, serviceName, methodName)
		case !method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			p("    public IAsyncEnumerable<%s> %sAsync(%s request, CallOptions? options = null, CancellationToken ct = default)",
				outputType, methodName, inputType)
			p("        => _channel.ServerStreamAsync<%s, %s>(%sMethods.%s, request, options, ct);",
				inputType, outputType, serviceName, methodName)
		case method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			p("    public ClientStreamCall<%s, %s> %sAsync(CallOptions? options = null, CancellationToken ct = default)",
				inputType, outputType, methodName)
			p("        => _channel.ClientStreamAsync<%s, %s>(%sMethods.%s, options, ct);",
				inputType, outputType, serviceName, methodName)
		case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			p("    public BidiStreamCall<%s, %s> %sAsync(CallOptions? options = null, CancellationToken ct = default)",
				inputType, outputType, methodName)
			p("        => _channel.BidiStreamAsync<%s, %s>(%sMethods.%s, options, ct);",
				inputType, outputType, serviceName, methodName)
		}
		p("")
	}
	p("}")
	p("")

	// --- Server Base Class ---
	p("// --- Server ---")
	p("")
	p("public abstract class %sBase", serviceName)
	p("{")
	for _, method := range service.Methods {
		methodName := string(method.GoName)
		inputType := csharpMessageType(method.Input)
		outputType := csharpMessageType(method.Output)

		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			p("    public virtual Task<%s> %s(%s request, ConnectContext context)",
				outputType, methodName, inputType)
			p("        => throw new ConnectException(ConnectCode.Unimplemented, \"%s is not implemented\");",
				methodName)
		case !method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			p("    public virtual IAsyncEnumerable<%s> %s(%s request, ConnectContext context, CancellationToken ct = default)",
				outputType, methodName, inputType)
			p("        => throw new ConnectException(ConnectCode.Unimplemented, \"%s is not implemented\");",
				methodName)
		case method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			p("    public virtual Task<%s> %s(IAsyncEnumerable<%s> requests, ConnectContext context)",
				outputType, methodName, inputType)
			p("        => throw new ConnectException(ConnectCode.Unimplemented, \"%s is not implemented\");",
				methodName)
		case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			p("    public virtual IAsyncEnumerable<%s> %s(IAsyncEnumerable<%s> requests, ConnectContext context, CancellationToken ct = default)",
				outputType, methodName, inputType)
			p("        => throw new ConnectException(ConnectCode.Unimplemented, \"%s is not implemented\");",
				methodName)
		}
		p("")
	}
	p("}")
	p("")

	// --- Service Definition ---
	p("public class %sDefinition : IConnectServiceDefinition", serviceName)
	p("{")
	p("    public static %sDefinition Instance { get; } = new();", serviceName)
	p("    public string ServiceName => %sMethods.ServiceName;", serviceName)
	p("    public IReadOnlyList<ConnectMethodDescriptor> Methods { get; } = new ConnectMethodDescriptor[]")
	p("    {")

	for i, method := range service.Methods {
		methodName := string(method.GoName)
		inputType := csharpMessageType(method.Input)
		outputType := csharpMessageType(method.Output)
		comma := ","
		if i == len(service.Methods)-1 {
			comma = ""
		}

		switch {
		case !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			// Unary
			p("        new ConnectMethodDescriptor(")
			p("            %sMethods.%s,", serviceName, methodName)
			p("            %s.Parser,", inputType)
			if isNoSideEffects(method) {
				// idempotency_level = NO_SIDE_EFFECTS: the server additionally exposes
				// this method over HTTP GET.
				p("            handler: async (svc, req, ctx) => (IMessage)await ((%sBase)svc).%s((%s)req, ctx),",
					serviceName, methodName, inputType)
				p("            isNoSideEffects: true)%s", comma)
			} else {
				p("            handler: async (svc, req, ctx) => (IMessage)await ((%sBase)svc).%s((%s)req, ctx))%s",
					serviceName, methodName, inputType, comma)
			}
		case !method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			// Server streaming
			p("        new ConnectMethodDescriptor(")
			p("            %sMethods.%s,", serviceName, methodName)
			p("            %s.Parser,", inputType)
			p("            methodType: ConnectMethodType.ServerStreaming,")
			p("            serverStreamHandler: (svc, req, ctx) => ConvertStream(((%sBase)svc).%s((%s)req, ctx)))%s",
				serviceName, methodName, inputType, comma)
		case method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer():
			// Client streaming
			p("        new ConnectMethodDescriptor(")
			p("            %sMethods.%s,", serviceName, methodName)
			p("            %s.Parser,", inputType)
			p("            methodType: ConnectMethodType.ClientStreaming,")
			p("            clientStreamHandler: async (svc, reqs, ctx) => (IMessage)await ((%sBase)svc).%s(ConvertStream<%s>(reqs), ctx))%s",
				serviceName, methodName, inputType, comma)
		case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
			// Bidi streaming
			p("        new ConnectMethodDescriptor(")
			p("            %sMethods.%s,", serviceName, methodName)
			p("            %s.Parser,", inputType)
			p("            methodType: ConnectMethodType.BidiStreaming,")
			p("            bidiStreamHandler: (svc, reqs, ctx) => ConvertStream(((%sBase)svc).%s(ConvertStream<%s>(reqs), ctx)))%s",
				serviceName, methodName, inputType, comma)
		}
		_ = outputType // used in the patterns above indirectly
	}

	p("    };")
	p("")

	// Check if we need ConvertStream helpers
	hasServerOrBidi := false
	hasClientOrBidi := false
	for _, method := range service.Methods {
		if method.Desc.IsStreamingServer() {
			hasServerOrBidi = true
		}
		if method.Desc.IsStreamingClient() {
			hasClientOrBidi = true
		}
	}

	if hasServerOrBidi {
		p("    private static async IAsyncEnumerable<IMessage> ConvertStream<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage")
		p("    {")
		p("        await foreach (var item in source.WithCancellation(ct))")
		p("            yield return item;")
		p("    }")
		p("")
	}

	if hasClientOrBidi {
		p("    private static async IAsyncEnumerable<T> ConvertStream<T>(IAsyncEnumerable<IMessage> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage")
		p("    {")
		p("        await foreach (var item in source.WithCancellation(ct))")
		p("            yield return (T)item;")
		p("    }")
		p("")
	}

	p("}")
}

// isNoSideEffects reports whether the method is declared side-effect free via
// `option idempotency_level = NO_SIDE_EFFECTS;`.
func isNoSideEffects(method *protogen.Method) bool {
	opts, ok := method.Desc.Options().(*descriptorpb.MethodOptions)
	return ok && opts.GetIdempotencyLevel() == descriptorpb.MethodOptions_NO_SIDE_EFFECTS
}

// csharpMessageType returns the C# type name for a protobuf message.
// Since the generated code lives in the same namespace as the proto-generated types,
// we just use the simple name.
func csharpMessageType(message *protogen.Message) string {
	// Use the Go name which matches the C# generated name for simple cases
	return string(message.GoIdent.GoName)
}

