// Code generated by protoc-gen-connect-csharp. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using ConnectNet;
using ConnectNet.Client;
using ConnectNet.Server;
using Google.Protobuf;

namespace ConnectNet.Tests.Proto;

public static class GreeterServiceMethods
{
    public const string ServiceName = "example.GreeterService";
    public const string SayHello = "/example.GreeterService/SayHello";
    public const string SayHelloStream = "/example.GreeterService/SayHelloStream";
    public const string CollectHellos = "/example.GreeterService/CollectHellos";
    public const string Chat = "/example.GreeterService/Chat";
}

// --- Client ---

public interface IGreeterServiceClient
{
    Task<HelloResponse> SayHelloAsync(HelloRequest request, CallOptions? options = null, CancellationToken ct = default);
    IAsyncEnumerable<HelloResponse> SayHelloStreamAsync(HelloRequest request, CallOptions? options = null, CancellationToken ct = default);
    ClientStreamCall<HelloRequest, HelloResponse> CollectHellosAsync(CallOptions? options = null, CancellationToken ct = default);
    BidiStreamCall<HelloRequest, HelloResponse> ChatAsync(CallOptions? options = null, CancellationToken ct = default);
}

public class GreeterServiceClient : IGreeterServiceClient
{
    private readonly ConnectChannel _channel;
    public GreeterServiceClient(ConnectChannel channel) => _channel = channel;

    public Task<HelloResponse> SayHelloAsync(HelloRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.UnaryAsync<HelloRequest, HelloResponse>(GreeterServiceMethods.SayHello, request, options, ct);

    public IAsyncEnumerable<HelloResponse> SayHelloStreamAsync(HelloRequest request, CallOptions? options = null, CancellationToken ct = default)
        => _channel.ServerStreamAsync<HelloRequest, HelloResponse>(GreeterServiceMethods.SayHelloStream, request, options, ct);

    public ClientStreamCall<HelloRequest, HelloResponse> CollectHellosAsync(CallOptions? options = null, CancellationToken ct = default)
        => _channel.ClientStreamAsync<HelloRequest, HelloResponse>(GreeterServiceMethods.CollectHellos, options, ct);

    public BidiStreamCall<HelloRequest, HelloResponse> ChatAsync(CallOptions? options = null, CancellationToken ct = default)
        => _channel.BidiStreamAsync<HelloRequest, HelloResponse>(GreeterServiceMethods.Chat, options, ct);

}

// --- Server ---

public abstract class GreeterServiceBase
{
    public virtual Task<HelloResponse> SayHello(HelloRequest request, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "SayHello is not implemented");

    public virtual IAsyncEnumerable<HelloResponse> SayHelloStream(HelloRequest request, ConnectContext context, CancellationToken ct = default)
        => throw new ConnectException(ConnectCode.Unimplemented, "SayHelloStream is not implemented");

    public virtual Task<HelloResponse> CollectHellos(IAsyncEnumerable<HelloRequest> requests, ConnectContext context)
        => throw new ConnectException(ConnectCode.Unimplemented, "CollectHellos is not implemented");

    public virtual IAsyncEnumerable<HelloResponse> Chat(IAsyncEnumerable<HelloRequest> requests, ConnectContext context, CancellationToken ct = default)
        => throw new ConnectException(ConnectCode.Unimplemented, "Chat is not implemented");

}

public class GreeterServiceDefinition : IConnectServiceDefinition
{
    public static GreeterServiceDefinition Instance { get; } = new();
    public string ServiceName => GreeterServiceMethods.ServiceName;
    public IReadOnlyList<ConnectMethodDescriptor> Methods { get; } = new ConnectMethodDescriptor[]
    {
        new ConnectMethodDescriptor(
            GreeterServiceMethods.SayHello,
            HelloRequest.Parser,
            handler: async (svc, req, ctx) => (IMessage)await ((GreeterServiceBase)svc).SayHello((HelloRequest)req, ctx)),
        new ConnectMethodDescriptor(
            GreeterServiceMethods.SayHelloStream,
            HelloRequest.Parser,
            methodType: ConnectMethodType.ServerStreaming,
            serverStreamHandler: (svc, req, ctx) => ConvertStream(((GreeterServiceBase)svc).SayHelloStream((HelloRequest)req, ctx))),
        new ConnectMethodDescriptor(
            GreeterServiceMethods.CollectHellos,
            HelloRequest.Parser,
            methodType: ConnectMethodType.ClientStreaming,
            clientStreamHandler: async (svc, reqs, ctx) => (IMessage)await ((GreeterServiceBase)svc).CollectHellos(ConvertStream<HelloRequest>(reqs), ctx)),
        new ConnectMethodDescriptor(
            GreeterServiceMethods.Chat,
            HelloRequest.Parser,
            methodType: ConnectMethodType.BidiStreaming,
            bidiStreamHandler: (svc, reqs, ctx) => ConvertStream(((GreeterServiceBase)svc).Chat(ConvertStream<HelloRequest>(reqs), ctx)))
    };

    private static async IAsyncEnumerable<IMessage> ConvertStream<T>(IAsyncEnumerable<T> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage
    {
        await foreach (var item in source.WithCancellation(ct))
            yield return item;
    }

    private static async IAsyncEnumerable<T> ConvertStream<T>(IAsyncEnumerable<IMessage> source, [EnumeratorCancellation] CancellationToken ct = default) where T : IMessage
    {
        await foreach (var item in source.WithCancellation(ct))
            yield return (T)item;
    }

}
